<?php


final class Designer extends Employee implements SalaryAmount {

    public function __construct(string $fullName, float $salary, string $qualification)
    {
        parent::__construct($fullName, $salary, $qualification);
    }

    public function getFullName(): string
    {
        return parent::getFullName(); // TODO: Change the autogenerated stub
    }

    public function getSalary(): float
    {
        return parent::getSalary(); // TODO: Change the autogenerated stub
    }

    public function getSalaryAmount(): float
    {
        return $this->getSalary();
    }
}