<?php


final class MiddleDeveloper extends Employee implements SalaryAmount {
    private $months;

    public function __construct(string $fullName, float $salary, int $months, string $qualification)
    {
        parent::__construct($fullName, $salary, $qualification);
        $this->months = $months;
    }

    public function getFullName(): string
    {
        return parent::getFullName(); // TODO: Change the autogenerated stub
    }

    public function getSalary(): float
    {
        return parent::getSalary(); // TODO: Change the autogenerated stub
    }

    public function getSalaryAmount(): float
    {
        return $this->months * $this->getSalary();
    }
}